export { default as AboutCompany } from './ui/AboutCompany.vue'
export { default as Projects } from './ui/Projects.vue'
export { default as KeyMetrics } from './ui/KeyMetrics.vue'
export { default as FlagshipSolutions } from './ui/FlagshipSolutions.vue'
export { default as ArticlesShowcase } from './ui/ArticlesShowcase.vue'
export { default as ProductsShowcase } from './ui/ProductsShowcase.vue'
export { default as FAQSection } from './ui/FAQSection.vue'
export { default as Reviews } from './ui/Reviews.vue'
export { default as Courses } from './ui/Courses.vue'
export { default as FastTrack } from './ui/FastTrack.vue'
export * from './hook/useAboutCompany'
export * from './hook/useProjects'
export * from './hook/useKeyMetrics'
export * from './hook/useReviews'
export * from './hook/useCourses'
export * from './hook/useArticles'
export * from './hook/useProducts'
export * from './hook/useFAQ'

